SUPABASE_URL = "https://zvzaqdxplitpcmvmwuch.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2emFxZHhwbGl0cGNtdm13dWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxMzAwODksImV4cCI6MjEwNDcwNjA4OX0.plB2tBuhQRHhKr2IF2e7i2NqILB0mBxHGUxRmkIainc"
